apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-rhel-10
  namespace: unipol-vm
  labels:
    kubevirt.io/vm: test-rhel-10
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-rhel-10
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cdromiso
              bootOrder: 2
              cdrom:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: test-rhel-10-dv
        - name: cdromiso
          dataVolume:
            name: rhel-10-iso